### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by birdsetfree** [tonipohl/AzureManagement#1]
Out-File : Cannot bind argument to parameter 'FilePath' because it is null.
At C:\Temp\SubscriptionRepository.ps1:7 char:14
+         | out-file $OutFilePath -encoding ascii
+                    ~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Out-File], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.OutFileComm
   and

**Comment by tonipohl** [comment]
Thx, fixed the variable name!
